version: '2'
services:
  web-1:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build: .
    links:
      - redis
    ports:
      - '8081:3000'
  web-2:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build: .
    links:
      - redis
    ports:
      - '8082:3000'
  redis:
    image: redis