---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: laundree-buddes
  annotations:
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "md5"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - buddes.dk
    secretName: buddes-tls
  rules:
  - host: buddes.dk
    http:
      paths:
        - backend:
            serviceName: laundree-master
            servicePort: 3000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: laundree-buddes-beta
  annotations:
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "md5"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - beta.buddes.dk
    secretName: buddes-beta-tls
  rules:
  - host: beta.buddes.dk
    http:
      paths:
        - backend:
            serviceName: laundree-beta
            servicePort: 3000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: laundree-beta
  annotations:
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "md5"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - beta.laundree.io
    secretName: laundree-beta-tls
  rules:
  - host: beta.laundree.io
    http:
      paths:
        - backend:
            serviceName: laundree-beta
            servicePort: 3000
