web:
  port: 'PORT'
  host: 'HOST'

redis:
  host: 'REDIS_HOST'
  port: 'REDIS_PORT'

opbeat:
  appId: 'OPBEAT_APP_ID'
  organizationId: 'OPBEAT_ORGANIZATION_ID'
  secretToken: 'OPBEAT_SECRET_TOKEN'

mongo:
  url: 'MONGO_URL'

facebook:
  appId: 'FACEBOOK_APP_ID'
  appSecret: 'FACEBOOK_APP_SECRET'
  callbackUrl: 'FACEBOOK_CALLBACK_URL'

google:
  clientApiKey: 'GOOGLE_CLIENT_API_KEY'
  serverApiKey: 'GOOGLE_SERVER_API_KEY'
  clientId: 'GOOGLE_CLIENT_ID'
  clientSecret: 'GOOGLE_CLIENT_SECRET'
  callbackUrl: 'GOOGLE_CALLBACK_URL'

session:
  secret: 'SESSION_SECRET'

codeClimate:
  repoToken: 'CODECLIMATE_REPO_TOKEN'

sauceLabs:
  username: 'SAUCE_LABS_USERNAME'
  accessKey: 'SAUCE_LABS_ACCESS_KEY'

mailer:
  smtp:
    transport: 'MAILER_SMTP_TRANSPORT'

mode: 'MODE'

oneSignal:
  appId: 'ONE_SIGNAL_APP_ID'
  restApiKey: 'ONE_SIGNAL_REST_API_KEY'
