web:
  port: 3000

redis:
  host: 'localhost'
  port: 6379

mailer:
  stubTransporter: false
  dryRun: false
  smtp:
    transport: 'smtps://user%40gmail.com:pass@smtp.gmail.com'

logging:
  http:
    enabled: true
    format: 'dev'
  error:
    enabled: true

sass:
  outputStyle: 'extended'

mongo:
  url: 'mongodb://localhost/laundree'

opbeat:
  enable: false
  trackRelease: false
  appId: null
  organizationId: null
  secretToken: null


facebook:
  appId: '0000000000000000'
  appSecret: '00000000000000000000000000000000'
  callbackUrl: 'https://someUrl/auth/facebook/callback'

google:
  clientId: '0000000000000000000000000000000000000000000000.apps.googleusercontent.com'
  clientSecret: '000000000000000000000000'
  callbackUrl: 'https://someUrl/auth/google/callback'

session:
  secret: 'secret1234'

security:
  password:
    saltRounds: 10

swagger:

  fittingsDirs: [ api/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ api/mocks ]
      controllersDirs: [ api/controllers ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true

    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_security
      - swagger_params_parser
      - _swagger_validate
      - express_compatibility
      - _router

    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw
